name: cytopia
summary: Cytopia is a free, open source retro pixel-art city building game
description: |
  Cytopia is a free, open source retro pixel-art city building game with a big 
  focus on mods. It utilizes a custom isometric rendering engine based on SDL2.
adopt-info: cytopia
base: core24
license: GPL-3.0
confinement: strict
compression: lzo
source-code: https://github.com/CytopiaTeam/Cytopia
issues: https://github.com/kz6fittycent/Cytopia/issues
contact: https://github.com/kz6fittycent/Cytopia
icon: snap/local/cytopia.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
apps:
  cytopia:
    command: bin/cytopia
    extensions: [gnome]
    after: 
      - conan
      - sdl2
      - sdl2-image
      - sdl2-ttf
    plugs:
      - home
      - network
      - joystick
      - opengl
      - audio-playback     

parts:
  cytopia:
    source: https://github.com/CytopiaTeam/Cytopia
    source-type: git
    plugin: cmake
    build-packages:
      - libopenal1
      - zlib1g
      - libnoise0
      - libvorbis0a
      - libpng16-16t64
      - libimgui-dev
      - python3
      - sdl2
      - sdl2-images
      - sdl2-ttf
      - conan
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"    
      
  conan:
    plugin: dump
    source: https://github.com/conan-io/conan/releases/download/2.10.1/conan-2.10.1-amd64.deb
    source-type: deb  
    
  sdl2:
    plugin: cmake
    source: https://github.com/libsdl-org/SDL
    source-type: git  
    
  sdl2-image:
    plugin: cmake
    source: https://github.com/libsdl-org/SDL_image
    source-type: git   
    
  sdl2-ttf:
    plugin: cmake
    source: https://github.com/libsdl-org/SDL_ttf
    source-type: git 
